export default {
  // menu
  "h_item1": "Dashboard",
  "h_item2": "Projects",
  "h_item3": "Tokens",
  "h_item4": "NFTs",
  "h_item5": "Blindbox",
  "h_item6": "Airdrop",
  "h_item7": "Vesting",
  "h_item8": "Lock Explore",
  "h_item9": "Sale Square",
  "h_item10": "Solution",
  //search
  "h_item11": "Enter token name or symbol",
  //copy
  "h_item12": "Copy",
  "h_item13": "Copied",
  //popup-login
  "h_item14": "Coming Soon",
  "h_item15": "Connect Wallet",
  "h_item16": "Connection Fail",
  "h_item17": "Confirm connection to BSC main network",
  "h_item18": "Confirm connection to BSC test network",
  "h_item19": "Account",
  "h_item20": "Change",
  "h_item21": "Disconnect",
  "h_item22": "Update Description",
  "h_item23": "Confirming...",
  "h_item24": "Operation Successful!",
  "h_item25": "Operation Failed!",
  "h_item26": "Operation Cancelled!",
  "h_item27": "Transaction Submitted!",
  "h_item28": "View Transaction",
  "h_item29": "No Data",
  "h_item30": "View",
  "h_item31": "Connected ",
  //popup-EditName
  "h_item32": "Update Project Name",
  "h_item33": "Confirm",
  "h_item34": "Update Success",
  //popup-Renew
  "h_item35": "Please choose the renewal package",
  "h_item36": "Service renewal",
  "h_item37": "Choose a renewal period",
  "h_item38": " month",
  //popup-TokenList
  "h_item39": "Update List",
  "h_item40": "A large version number is required to add/remove tokens",
  "h_item41": "Add the Chinese version number after editing the token",
  "h_item42": "Push Updates",
  //popup-UpdateFee
  "h_item43": "Factory contracts cannot be empty",
  "h_item44": "The Fee address cannot be empty",
  "h_item45": "Update fee address",
  "h_item46": "Fee address",
  "h_item47": "Enter wallet address",
  "h_item48": "If the transaction address is set, 0.05% of the transaction fee will be paid, otherwise 0.3% of the transaction fee will be awarded to LPs.  ",
  //popup-BoxCoin
  "h_item49": "NFT contract address cannot be empty",
  "h_item50": "The amout of mint  must be greater than 0",
  "h_item51": "The amount of remaining mintable is insufficient",
  "h_item52": "The receiving address cannot be empty",
  "h_item53": "Mint blind box",
  "h_item54": "Amount",
  "h_item55": "Remaining",
  "h_item56": "Receiving address",
  "h_item57": "Enter receiving address",
  "h_item58": "The entered address is incorrect",
  //popup-BoxView
  "h_item59": "View",
  //popup-Coin
  "h_item60": "Mint NFT",
  //popup-Status
  "h_item61": "Operation Status",
  "h_item62": "Please confirm and send the transaction in the wallet",
  "h_item63": "Operation Cancelled!",
  "h_item64": "Operation Successful!",
  "h_item65": "Operation Failed!",
  "h_item66": "Transaction Submitted!",
  //popup-TransferNft
  "h_item67": "TokenId Required",
  "h_item68": "Gift",
  "h_item69": "Receiving Address",
  // admin-Admin
  "h_item70": "Projects",
  "h_item71": "Tokens",
  "h_item72": "Blindbox",
  "h_item73": "Manage",
  "h_item74": "Functions",
  "h_item75": "Create Tokens",
  "h_item76": "Create NFTs",
  "h_item77": "Create Blindbox",
  "h_item78": "Airdrop",
  "h_item79": "Address List",
  //admin-Schemeawait
  "h_item80": "Decentralized exchanges",
  "h_item81": "A decentralized exchange with a private AMM automatic market-making mechanism immediately after opening.  ",
  "h_item82": "View Details",
  "h_item83": "Decentralized NFT Market",
  "h_item84": "Immediately after the launch, there was a private decentralized NFT market.",
  "h_item85": "Liquidity Mining",
  "h_item86": "Immediately after opening, it has a set of liquidity mining solutions, supporting LP and single currency mining, and customized mining currency.",
  // solutionadmin-Dex
  "h_item87": "Service period to",
  "h_item88": "Deleted",
  "h_item89": "Renew",
  "h_item90": "Dex Token list",
  "h_item91": "Symbol",
  "h_item92": "Search",
  "h_item93": "Add Tokens",
  "h_item94": "Chain",
  "h_item95": "Decimal",
  "h_item96": "Tokens Contract Address",
  "h_item97": "Delete",
  "h_item98": "Dex Admin",
  "h_item99": "NFT Admin",
  "h_item100": "Farm Admin",
  // solutionadmin-add
  "h_item101": "Please enter the Token Symbol  ",
  "h_item102": "Please upload pictures",
  "h_item103": "Tokens Icon",
  "h_item104": "Contract",
  "h_item105": "Token Name",
  "h_item106": "Token Symbols",
  "h_item107": "Added successfully",
  // solution-solution
  "h_item108": "Opened",
  "h_item109": "Not opened",
  // solution-open
  "h_item110": "Please fill in the required fields",
  "h_item111": "Open",
  "h_item112": "Set",
  "h_item113": "Deploy",
  "h_item114": "Deployment is complete",
  "h_item115": "Name",
  "h_item116": "Subdomain Prefix",
  "h_item117": "Logo",
  "h_item118": "Upload JPG, PNG, or GIF images of 268 × 72px size up to 500KB  ",
  "h_item119": "Fee address",
  "h_item120": "A one-sentence introduction",
  "h_item121": "A few words about your",
  "h_item122": "Service period",
  "h_item123": "Next",
  "h_item124": "Deployment Project",
  "h_item125": "Factory Contract",
  "h_item126": "Routing Contracts",
  "h_item127": "The front-end deployment",
  // solution-detail
  "h_item128": "Back",
  "h_item129": "Function",
  "h_item130": "Tokens Swap",
  "h_item131": "Pool management",
  "h_item132": "Advantage",
  "h_item133": "One-click enable enables automatic deployment",
  "h_item134": "Complete front-end rendering without server",
  "h_item135": "Case",
  "h_item136": "Service Fee",
  "h_item137": "NFT bill fixed price transaction",
  "h_item138": "NFT bidding transaction",
  "h_item139": "LP Mining",
  "h_item140": "Single Token Mining",
  "h_item141": "One-click opening, automatic deployment, custom configuration of the mining pool",
  //nfts-nfts
  "h_item142": "I Creat",
  "h_item143": "I Hold",
  "h_item144": "Purpose",
  "h_item145": "Private",
  "h_item146": "Sell",
  "h_item147": "Total",
  "h_item148": "Remaining",
  "h_item149": "Open Source",
  "h_item150": "Mint",
  "h_item151": "Contract",
  "h_item152": "Contract",
  "h_item153": "Max single-pass 10",
  //nfts-hold
  "h_item154": "Transfer",
  //nfts-add
  "h_item155": "NFT Type",
  "h_item156": "Basic",
  "h_item157": "Advanced",
  "h_item158": "Temporarily not opened",
  "h_item159": "NFT Image",
  "h_item160": "NFT Name",
  "h_item161": "NFT Symbol",
  "h_item162": "NFT Introduce",
  "h_item163": "The total number of issues cannot be greater than an 18-digit positive integer",
  //blindbox-hold
  "h_item164": "Open",
  //blindbox-add
  "h_item165": "Can't add",
  "h_item166": "Can't delete it",
  "h_item167": "The current NFT has been added",
  "h_item168": "Please select NFT and enter amount",
  "h_item169": "Blindbox Image",
  "h_item170": "Blindbox Name",
  "h_item171": "Blindbox Symbol",
  "h_item172": "Insert NFT",
  "h_item173": "Select NFT",
  "h_item174": "Amount",
  "h_item175": "Remaining",
  "h_item176": "Insert Other NFT",
  "h_item177": "Blindbox Introduce",
  "h_item178": "The remaining is insufficient",
  "h_item179": "Please connect to the platform supported chain",
}
