export default {
  // menu
  "h_item1": "常用面板",
  "h_item2": "项目管理",
  "h_item3": "通证管理",
  "h_item4": "NFT管理",
  "h_item5": "盲盒管理",
  "h_item6": "空投管理",
  "h_item7": "团队归属",
  "h_item8": "锁仓浏览器",
  "h_item9": "销售广场",
  "h_item10": "解决方案",
  //search
  "h_item11": "请输入代币名称或符号",
  //copy
  "h_item12": "复制地址",
  "h_item13": "复制成功",
  //popup-login
  "h_item14": "敬请期待",
  "h_item15": "连接钱包",
  "h_item16": "连接失败",
  "h_item17": "请连接 BSC 主网络",
  "h_item18": "请连接 BSC 测试网络",
  "h_item19": "账户",
  "h_item20": "更改",
  "h_item21": "断开",
  "h_item22": "修改项目介绍",
  "h_item23": "确认中...",
  "h_item24": "操作成功！",
  "h_item25": "操作失败",
  "h_item26": "操作取消",
  "h_item27": "交易已提交，请等待...",
  "h_item28": "查看交易",
  "h_item29": "暂无数据",
  "h_item30": "在浏览器上查看",
  "h_item31": "已连接",
  //popup-EditName
  "h_item32": "修改项目名称",
  "h_item33": "确认",
  "h_item34": "更新成功",
  //popup-Renew
  "h_item35": "请选择续费套餐",
  "h_item36": "服务续费",
  "h_item37": "选择续费期限",
  "h_item38": "个月",
  //popup-TokenList
  "h_item39": "更新代币列表",
  "h_item40": "添加/删除代币时需要增加大版本号",
  "h_item41": "编辑代币后需要增加中版本号",
  "h_item42": "推送更新",
  //popup-UpdateFee
  "h_item43": "工厂合约不能为空",
  "h_item44": "手续费地址不能为空",
  "h_item45": "修改手续费地址",
  "h_item46": "手续费地址",
  "h_item47": "输入钱包地址",
  "h_item48": "若设置手续费地址，则将收入0.05%的交易手续费，否则0.3%的交易手续费都将奖励LP。",
  //popup-BoxCoin
  "h_item49": "NFT合约地址必传",
  "h_item50": "铸造数量必须大于0",
  "h_item51": "剩余可铸数量不足",
  "h_item52": "接收地址必传",
  "h_item53": "铸出盲盒",
  "h_item54": "铸币数量",
  "h_item55": "剩余可铸",
  "h_item56": "接收钱包地址",
  "h_item57": "输入接收钱包地址",
  "h_item58": "输入的钱包地址不正确",
  //popup-BoxView
  "h_item59": "查看NFT",
  //popup-Coin
  "h_item60": "铸出NFT",
  //popup-Status
  "h_item61": "操作状态",
  "h_item62": "请在钱包中确认并发送交易",
  "h_item63": "操作取消",
  "h_item64": "操作成功",
  "h_item65": "操作失败",
  "h_item66": "交易已提交，等待确认",
  //popup-TransferNft
  "h_item67": "tokenId 必传",
  "h_item68": "转让NFT",
  "h_item69": "接收地址",
  // admin-Admin
  "h_item70": "项目",
  "h_item71": "代币",
  "h_item72": "盲盒",
  "h_item73": "进入管理后台",
  "h_item74": "常用功能",
  "h_item75": "发行代币",
  "h_item76": "发行NFT",
  "h_item77": "发行盲盒",
  "h_item78": "空投代币",
  "h_item79": "名单管理",
  //admin-Schemeawait
  "h_item80": "去中心化交易所",
  "h_item81": "开通后立即拥有一套私有的AMM自动做市机制的去中心化交易所。",
  "h_item82": "查看详情",
  "h_item83": "去中心化NFT交易所",
  "h_item84": "开通后立即拥有一套私有的去中心化NFT交易所。",
  "h_item85": "流动性挖矿",
  "h_item86": "开通后立即拥有一套流动性挖矿解决方案，支持LP 和单币挖矿，自定义产矿币种。",
  // solutionadmin-Dex
  "h_item87": "服务期至",
  "h_item88": "删除成功",
  "h_item89": "续费",
  "h_item90": "Dex代币白名单列表",
  "h_item91": "代币符号",
  "h_item92": "搜索",
  "h_item93": "添加代币",
  "h_item94": "发行链",
  "h_item95": "精度",
  "h_item96": "代币地址",
  "h_item97": "删除",
  "h_item98": "Dex管理后台",
  "h_item99": "NFT管理后台",
  "h_item100": "Farm管理后台",
  // solutionadmin-add
  "h_item101": "请输入Token",
  "h_item102": "请添加图片",
  "h_item103": "代币图标",
  "h_item104": "代币合约地址",
  "h_item105": "代币名称",
  "h_item106": "代币符号",
  "h_item107": "添加成功",
  // solution-solution
  "h_item108": "已开通",
  "h_item109": "未开通",
  // solution-open
  "h_item110": "请填写必填项",
  "h_item111": "开通",
  "h_item112": "配置",
  "h_item113": "部署",
  "h_item114": "部署完成",
  "h_item115": "名称",
  "h_item116": "子域名前缀",
  "h_item117": "图标",
  "h_item118": "上传268*72px的jpg、png或gif图片，大小不超过500kb",
  "h_item119": "手续费地址管理员",
  "h_item120": "一句话介绍",
  "h_item121": "简单介绍下您的",
  "h_item122": "服务期限",
  "h_item123": "下一步",
  "h_item124": "部署项目",
  "h_item125": "工厂合约",
  "h_item126": "路由合约",
  "h_item127": "前端部署",
  // solution-detail
  "h_item128": "返回",
  "h_item129": "功能",
  "h_item130": "代币兑换",
  "h_item131": "资金池管理",
  "h_item132": "优势",
  "h_item133": "一键开通，自动化部署",
  "h_item134": "无需提供服务器，完整前端呈现",
  "h_item135": "案例",
  "h_item136": "服务费",
  "h_item137": "NFT挂单固价交易",
  "h_item138": "NFT挂单竞价交易",
  "h_item139": "LP挖矿",
  "h_item140": "单币挖矿",
  "h_item141": "一键开通，自动化部署，矿池自定义配置",
  //nfts-nfts
  "h_item142": "我创建的",
  "h_item143": "我持有的",
  "h_item144": "用途",
  "h_item145": "自用",
  "h_item146": "销售",
  "h_item147": "发行总量",
  "h_item148": "剩余总量",
  "h_item149": "已开源",
  "h_item150": "铸出",
  "h_item151": "NFT合约地址",
  "h_item152": "盲盒合约地址",
  "h_item153": "单次铸出上限10个",
  //nfts-hold
  "h_item154": "转让",
  //nfts-add
  "h_item155": "NFT类型",
  "h_item156": "基础型",
  "h_item157": "进阶型",
  "h_item158": "暂未开放",
  "h_item159": "NFT图片",
  "h_item160": "NFT名称",
  "h_item161": "NFT符号",
  "h_item162": "NFT介绍",
  "h_item163": "发行总量不能大于18位正整数",
  //blindbox-hold
  "h_item164": "打开",
  //blindbox-add
  "h_item165": "不能添加了",
  "h_item166": "不能删除了",
  "h_item167": "已添加过当前NFT",
  "h_item168": "请选择塞入NFT的选项或填写数量",
  "h_item169": "盲盒图片",
  "h_item170": "盲盒名称",
  "h_item171": "盲盒符号",
  "h_item172": "塞入NFT",
  "h_item173": "选择NFT",
  "h_item174": "塞入数量",
  "h_item175": "剩余数量",
  "h_item176": "继续塞入NFT",
  "h_item177": "盲盒介绍",
  "h_item178": "剩余可用数量不足",
  "h_item179": "请连接到平台支持的链",
}
